#!/bin/sh

# Create webroot
mkdir -p /var/clearos/joomla/webroot

# Active Fleshare
/usr/sbin/flexshare -n webapp-joomla -a activate >/dev/null 2>&1

# Initialize database
/usr/sbin/systemdb joomla apache
